version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: hmblog
    ports:
      - "5497:5432"
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  db_data:
    driver: local
